.PHONY: all
all: precommit

.PHONY: deps
deps: .deps-installed

.deps-installed: {% if uses_uv%}pyproject.toml uv.lock{% endif +%}{% if uses_npm %} package.json package-lock.json{% endif +%}{% if uses_pre_commit %} .pre-commit-config.yaml .template_files/pre_push{% endif +%}
{% if uses_uv %}
	.template_files/uv_install_deps
{% endif %}
{% if uses_npm %}
	.template_files/npm_install_deps
{% endif %}
{% if uses_pre_commit %}
	.template_files/pre_commit_install
{% endif %}
	touch .deps-installed

# We run each 'update_deps' step twice, before and after updating the interpreter,
# in case existing package versions aren't compatible with the new interpreter.
.PHONY: deps_update
deps_update: deps
{% if uses_uv %}
	.template_files/uv_update_deps
	.template_files/uv_update_python
	.template_files/uv_update_deps
{% endif %}
{% if uses_npm %}
	.template_files/npm_update_deps
	.template_files/npm_update_node
	.template_files/npm_update_deps
{% endif %}
{% if uses_pre_commit %}
	uv run pre-commit autoupdate
{% endif %}
{% if uses_gha_update %}
	uv run gha-update
{% endif %}

.PHONY: precommit
precommit: deps
{% if uses_pre_commit %}
	uv run pre-commit run -a
{% endif %}

.PHONY: ci
ci: precommit test_slow

# Fast tests are run by pre-commit
.PHONY: test_fast
test_fast: deps
{% if uses_bats %}
	.template_files/bats --pretty --filter-tags !slow -r tests
{% endif %}
{% if uses_pytest %}
{% for version in python_versions | reverse %}
	uv run{% if version != max_python_version %} --isolated{% endif %}{% if max_python_version != min_python_version %} --python '{{ version }}'{% endif %} pytest -m 'not slow' tests
{% endfor %}
{% endif %}

# Slow tests are only run in CI
.PHONY: test_slow
test_slow: deps
{% if uses_bats %}
	.template_files/bats --pretty --filter-tags slow -r tests
{% endif %}
{% if uses_pytest %}
{% for version in python_versions | reverse %}
	uv run{% if version != max_python_version %} --isolated{% endif %}{% if max_python_version != min_python_version %} --python '{{ version }}'{% endif %} pytest -m slow tests
{% endfor %}
{% endif %}
{% if uses_copier %}

.PHONY: template_reapply
template_reapply: deps
	uv run copier update --trust --vcs-ref=:current:

.PHONY: template_update
template_update: deps
	uv run copier update --trust
{% endif %}

.PHONY: clean
clean:
	find . '(' -type f -name '*~' ')' -delete
	rm -f .deps-installed

.PHONY: deepclean
deepclean: clean
{% if uses_uv %}
	rm -rf .venv
{% endif %}
{% if uses_npm %}
	rm -rf node_modules
{% endif %}
{% if has_python %}
	find . -depth '(' -type d -name '__pycache__' ')' -exec rm -r '{}' ';'
{% endif %}
{% if uses_ruff %}
	rm -rf .ruff_cache
{% endif %}
{% if uses_mypy %}
	rm -rf .mypy_cache
{% endif %}
{% if uses_pytest %}
	rm -rf .pytest_cache .coverage
{% endif %}
