.PHONY: all
all: lint test

.PHONY: deps
deps: .deps-installed

.deps-installed: {% if uses_uv%}pyproject.toml uv.lock{% endif +%}{% if uses_npm %} package.json package-lock.json{% endif +%}
{% if uses_uv %}
	./.template_scripts/uv_install_deps.sh
{% endif %}
{% if uses_npm %}
	./.template_scripts/npm_install_deps.sh
{% endif %}
{% if uses_pre_commit %}
	uv run pre-commit install -f
{% endif %}
	touch .deps-installed

.PHONY: lint
lint: deps
{% if uses_pre_commit %}
	uv run pre-commit run -a
{% endif %}

.PHONY: test
test: deps

.PHONY: update_deps
update_deps: deps
{% if uses_uv %}
	./.template_scripts/uv_update_deps.sh
{% endif %}
{% if uses_npm %}
	./.template_scripts/npm_update_deps.sh
{% endif %}
{% if uses_pre_commit %}
	uv run pre-commit autoupdate
{% endif %}

{% if uses_copier %}
.PHONY: update_template
update_template: deps
	uv run copier update --trust
{% endif %}

.PHONY: clean
clean:
	find . '(' -type f -name '*~' ')' -delete
	rm -f .deps-installed

.PHONY: deepclean
deepclean: clean
{% if uses_uv %}
	rm -rf .venv
{% endif %}
{% if uses_npm %}
	rm -rf node_modules
{% endif %}
