# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 8cd0780
_src_path: .
author_name: Callie Cameron
copyright_start_year: '2025'
is_python_package: false
project_name: Copier template
project_version: 0.0.0
python_line_length: 88
user_has_css: true
user_has_html: true
user_uses_pytest: true
