# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.4-9-g67494a0
_src_path: .
author_name: Callie Cameron
copyright_start_year: '2025'
exports_requirements_txt: true
github_repo: calliecameron/copier-template
max_python_version: '3.14'
min_python_version: '3.12'
project_name: Copier template
