# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.2-5-gb61c5f4
_src_path: .
author_name: Callie Cameron
copyright_start_year: '2025'
exports_requirements_txt: true
github_repo: calliecameron/copier-template
is_python_package: false
project_name: Copier template
project_version: 0.0.0
python_line_length: 88
