# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.2-12-g7eab36f
_src_path: .
author_name: Callie Cameron
copyright_start_year: '2025'
exports_requirements_txt: true
github_repo: calliecameron/copier-template
project_name: Copier template
