#!/bin/bash

set -eu

THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ ! -e pyproject.toml ]; then
    echo 'Must be run in the root of the project' 2>&1
    exit 1
fi

uv run python "${THIS_DIR}/uv_update_deps_internal.py"
